Update natural numbers, notebook and efficiency_test
PMF-Data-Science/PMF-DataScience pull request #6
Opened 2021-11-13 21:59 UTC by dorotea17

2021-11-14 10:34 UTC, marjev requested changes
Imate još i testiranje ispravnosti. Provjerite je li vam taj test prolazi.
Ne vidim da ste njega mijenjali.

On bi vam se trebao nalaziti isto u tests direktoriju, ali pod direktorijem unit.

2021-11-14 10:34 UTC, marjev commented on code_measurement/project_euler/math_modules/natural_numbers.py
>  DIVISOR_MINUS_SEVEN = -7
Možete maknuti sad ove konstante, pošto se više ne koriste u modulu.
Prije smo ih imali tu jer smo izvlačili podatke iz funkcije (odvajali ih iz funkcionalnosti).

Ne trebaju vam niti izvan modula, možete slobodno kod pozivanja funkcije `get_natural_numbers_sum` poslati sve brojeve, npr.:
`get_natural_numbers_sum(-2, [2, 5], 2)`

2021-11-14 10:34 UTC, marjev commented on code_measurement/project_euler/math_modules/natural_numbers.py
> +    '''Sumiranje brojeva u rasponu od (donja_granica, gornja_granica) koji su djeljivi s barem jednim djeliteljom iz liste divisors'''
Kako ne bismo imali kod malo na hrvatskom, a malo na engleskom jeziku, bilo bi dobro imenovanje varijabli i docstringove pisati na engleskom jeziku.
Možete li samo prevesti ovo na engleski?

2021-11-14 10:34 UTC, marjev commented on code_measurement/project_euler/math_modules/natural_numbers.py
>      #divisors_set = set(np.random.randint(low=1,high=upper_limit,size=upper_limit - 1))
Možete i ovo slobodno maknuti.

2021-11-14 10:34 UTC, marjev commented on code_measurement/project_euler/math_modules/natural_numbers.py
> +      for number in range(lower_limit + 1, upper_limit) #budući da se ne uzima upper_limit, ne uzima se ni lower_limit
Umjesto ovog inline komentara, možete dodati ovu napomenu u docstring funkcije. Navedite kako su donja i gornja granica isključene.

> Sumiranje brojeva u rasponu od (donja_granica, gornja_granica), isključivo

ili matematički preciznije

> Sumiranje brojeva u intervalu od <donja_granica, gornja_granica>

2021-11-14 10:34 UTC, marjev commented on code_measurement/project_euler/math_modules/natural_numbers.py
>        #if sum(map((lambda x: number % x),divisors_set))
Možete i ovo maknuti.

2021-11-14 10:34 UTC, marjev commented on code_measurement/project_euler/tests/efficiency/efficiency_test.py
>          #return measurements_dict
Možete maknuti ove komentare.

2021-11-14 13:55 UTC, marjev commented on code_measurement/project_euler/tests/unit/test_natural_numbers.py
> +        self.assertEqual(get_natural_numbers_sum(lower_limit, divisors, upper_limit), sum(number for number in range(lower_limit+1,upper_limit) if any(not number % divisor for divisor in divisors )))
Pokušajte umjesto parametara izgenerirati nasumične vrijednosti prije assert linije za tri ulazna podatka (donju i gornju granicu te djelitelje).

2021-11-14 13:58 UTC, marjev commented on code_measurement/project_euler/math_modules/natural_numbers.py
> +    '''Summation of numbers in the range of <lower_limit, upper_limit> that are divisible by at least one divisor from the list of divisors'''
💯

2021-11-14 16:22 UTC, marjev commented on code_measurement/project_euler/tests/unit/test_natural_numbers.py
> +          divisors.append(randint(-10,10))
Za linije od 10-12 možete iskoristiti random.sample.
Zašto?
Ovo trenutno će vam:
1) potencijalno uključivati duplikate, ako se odabere isti broj više puta
2) potencijalno uključuje nulu, što će vam izbaciti grešku, jer dijeljenje s nulom nije dozvoljeno

Samo pripazite da s rangeom ne obuhvatite broj nula.

2021-11-14 16:23 UTC, marjev commented on code_measurement/project_euler/tests/unit/test_natural_numbers.py
> +        self.assertEqual(get_natural_numbers_sum(lower_limit, divisors, upper_limit), sum(number for number in range(lower_limit+1,upper_limit) if any(not number % divisor for divisor in divisors )))
savjetujem da ovaj drugi parametar
sum(number for number in range(lower_limit+1,upper_limit) if any(not number % divisor for divisor in divisors ))
napišete u liniji prije i spremite ga u varijablu.
Na taj način će vam ova linija biti čitljivija.

Nazovite varijablu npr. expected_result.

2021-11-16 09:22 UTC, marjev approved these changes

2021-11-16 10:13 UTC, SpaceXAlphaBravoCharlie approved these changes

2021-11-16 10:13 UTC, merged